### ISSUE TITLE
Mainnet Contract Config & Deployment

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/gitcoin-web#19]
Any code changes will be made in the [BulkTransactions](https://github.com/gitcoinco/BulkTransactions) repo

- [x] Pick & apply what version of solidity to use
- [x] Configuration for mainnet deployment
- [x] Validate Etherescan verification process works on testnet
- [x] Deploy to mainnet
- [x] Verify on mainnet Etherscan

**Comment by mds1** [comment]
Validated on Etherscan: https://rinkeby.etherscan.io/address/0x7d655c57f71464B6f83811C55D84009Cd9f5221C#code

**Comment by mds1** [comment]
Contract deployed to mainnet and verified: https://etherscan.io/address/0x7d655c57f71464B6f83811C55D84009Cd9f5221C

**Comment by mds1** [comment]
Mainnet and RInkeby contracts have the same address, so no additional configuration is needed
