### ISSUE TITLE
Question: What do we want to do once we get the tx hash of bulk checkout?

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/gitcoin-web#22]
Hey @mds1, presumably the question here is actually multi-part, right?

1. What to show once we've gotten the tx hash of the bulk checkout, but it's not yet been confirmed by the network?
2. What to do when we get the confirmation that the tx succeeded?

Assuming this is right, maybe you could comment @owocki ☝️

**Comment by owocki** [comment]
IMHO you just want to perform all these commands ( https://github.com/gitcoinco/web/blob/master/app/grants/views.py#L806-L871  AND https://github.com/gitcoinco/web/blob/master/app/grants/views.py#L880-L903 ). this is inclusive of sending an email, recording the info in the DB, etc.  perhaps many of them can be factored into their own helper methods..

@pixelantdesign can comment on what the user should see after they do the bulk checkout. im pretty sure theres a screen for that in the figma

**Comment by owocki** [comment]
> What to do when we get the confirmation that the tx succeeded?

lets assume optimistically that the tx will succeed. we have a "wait but it failed" email we can send later in the 'it failed' case

**Comment by owocki** [comment]
per https://www.figma.com/file/6OqyMtEfRU4vDMlZXO6Y3l/Gitcoin-Grants-Experience-2020?node-id=0%3A1 it looks like we want to drop them on the grants landing page with a kudos redemption? or do we want to do something else, maybe take them to their profile and show them all the new grants in their grants profile.  encourage them to share on twitter?

**Comment by owocki** [comment]
@pixelantdesign ^^

**Comment by PixelantDesign** [comment]
If the transaction is sucessful, we would display a confirmation and then redirect them to receive a kudos. 

<img width="1242" alt="Screen Shot 2020-06-09 at 7 56 26 PM" src="https://user-images.githubusercontent.com/238235/84212261-587d3c80-aa8b-11ea-8c70-8b185e2a99a8.png">

If we have the grants collection feature complete, then we would ask if they want to add those grants to a collection.

**Comment by apbendi** [comment]
Thanks @PixelantDesign, super helpful! @owocki, is that feature mentioned something someone is working on, or did it not make the cut this time around? With regards to Kudos, can you point us in the right direction with how to issue one of those/redirect to the Kudos page?

**Comment by mds1** [comment]
Closed by #64, which implements the redirect and alert. I believe the Kudos aspect will be implemented by @owocki in #55
