### ISSUE TITLE
Require Cart Login Before Bulk Grants Checkout

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/gitcoin-web#24]
Hey @owocki, this is one where we could use a hit to save us some time. What would be the easiest way to detect if the user is logged in or not, then redirect them to a login page from the cart if not.

**Comment by owocki** [comment]
`document.contxt['github_handle']` in JS will do it

**Comment by owocki** [comment]
`document.contxt['github_handle']` in JS will do it

**Comment by mds1** [comment]
Using JS, how can we redirect to the login screen and navigate back to the cart page after login?

**Comment by owocki** [comment]
send the user to '/login/github?next=' + REDIRECT_URL
