### ISSUE TITLE
Support Recurring Grants In Cart Checkout Page

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/gitcoin-web#28]
- [x] Update form to allow user to select multiple rounds
  - [x] Should *not* allow multi-round for ETH donations
- [ ] Grant contract interactions to fetch data needed for signature (pull from `fund.js`)
- [ ] Token approval
- [ ] Get user signature
- [ ] POST all needed data to backend

**Comment by mds1** [comment]
Closing since we decided not to support this for now
