### ISSUE TITLE
Implement "Add comment to owner" functionality

### ISSUE THREAD

**Issue by mds1** [ScopeLift/gitcoin-web#32]
The figma mockups show an "Add comment to owner" link for each item in the cart. This UI is implemented for this, but it's not currently functional

@owocki, Assuming you still want this functionality, how do we handle input that gets entered for this? Where in the code is this message currently handled? It looks like it's used in `fund.js` but I can't quite tell exactly how

cc @apbendi

**Comment by mds1** [comment]
From checking out the POST requests sent, it looks like this is just included as a `comment` field in the data sent with the POST required

**Comment by owocki** [comment]
yes, thats right.

it's in the same post-checkout code i sent you guys yesterday, in master grants/views.py, line 843

**Comment by mds1** [comment]
Closed by #36
