### ISSUE TITLE
SMS code throws error on the cart page when not logged in

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/gitcoin-web#41]
When not logged in, the cart page now throws errors, related to the SMS feature. @zoek1 mind taking a look? Thanks!

![IMAGE 2020-06-09 23:36:16](https://user-images.githubusercontent.com/1479802/84224266-04358500-aaaa-11ea-9632-8eeafa352ae2.jpg)

**Comment by mds1** [comment]
Closed by #43
