### ISSUE TITLE
Wire "Sustain These Grants" button to bulk grants functionality

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/gitcoin-web#69]
<img width="1092" alt="Screen Shot 2020-06-10 at 9 48 05 PM" src="https://user-images.githubusercontent.com/1479802/84335963-2e4b7d80-ab64-11ea-9c07-63bdf37d79f9.png">

With #68

**Comment by apbendi** [comment]
Hey @owocki, did you want to tackle this or should I take a stab?

**Comment by owocki** [comment]
@apbendi i already coded it on the grants-round-6 integrarion branch

**Comment by apbendi** [comment]
> @apbendi i already coded it on the grants-round-6 integrarion branch

Oh great, way ahead of me 😎
