### ISSUE TITLE
phone number hash is always the same even if number is different

### ISSUE THREAD

**Issue by owocki** [ScopeLift/gitcoin-web#78]
https://bits.owocki.com/9ZujNkA4

**Comment by owocki** [comment]
@zoek1 this is from grants-round-6-integraiton brnach as of today

**Comment by zoek1** [comment]
This was fixed also in https://github.com/gitcoinco/web/pull/6839
![image](https://user-images.githubusercontent.com/660973/84542013-2c95cd00-acbe-11ea-8762-2cdba68c4bc9.png)
